# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calculateESCpp <- function(score, inSet, scoreType) {
    .Call(`_CoCoRV_calculateESCpp`, score, inSet, scoreType)
}

calculateESCppFast <- function(score, inSet, scoreType, p, returnLeadingEdge) {
    .Call(`_CoCoRV_calculateESCppFast`, score, inSet, scoreType, p, returnLeadingEdge)
}

GSEACpp <- function(pathway, scoresNull, nGenes, nReplicate, scoreObserved, scoreType, maxExtreme, maxPermutation, p) {
    .Call(`_CoCoRV_GSEACpp`, pathway, scoresNull, nGenes, nReplicate, scoreObserved, scoreType, maxExtreme, maxPermutation, p)
}

calculateProbCpp <- function(p) {
    .Call(`_CoCoRV_calculateProbCpp`, p)
}

oddsRatioToParCpp <- function(ORPar) {
    .Call(`_CoCoRV_oddsRatioToParCpp`, ORPar)
}

dmultinomCpp <- function(observed, probability, useLog = FALSE) {
    .Call(`_CoCoRV_dmultinomCpp`, observed, probability, useLog)
}

negativeLogLikCpp <- function(par, data) {
    .Call(`_CoCoRV_negativeLogLikCpp`, par, data)
}

negativeLogLikGenotypeCpp <- function(par, data) {
    .Call(`_CoCoRV_negativeLogLikGenotypeCpp`, par, data)
}

negativeLogLikGradCpp <- function(par, data) {
    .Call(`_CoCoRV_negativeLogLikGradCpp`, par, data)
}

negativeLogLikGenotypeGradCpp <- function(par, data) {
    .Call(`_CoCoRV_negativeLogLikGenotypeGradCpp`, par, data)
}

twoSidedP <- function(p) {
    .Call(`_CoCoRV_twoSidedP`, p)
}

